- hosts: localhost
  pre_tasks:
    - name: Update apt repositories
      apt:
        update_cache: true
      become: true
      tags:
        - dotfiles
        - bat
        - fzf
        - tmux
  tasks:
    - import_tasks: tasks/dotfiles.yml
    - import_tasks: tasks/ssh.yml
    - import_tasks: tasks/bat.yml
    - import_tasks: tasks/docker.yml
      become: true
    - import_tasks: tasks/git.yml
      become: true
    - import_tasks: tasks/fzf.yml
    - import_tasks: tasks/tmux.yml
    - import_tasks: tasks/asdf.yml
    - import_tasks: tasks/terraform.yml
      become: true
