- hosts: localhost
  pre_tasks:
    - name: Update apt repositories
      apt:
        update_cache: true
      become: true
      tags:
        - dotfiles
        - bat
        - fzf
        - tmux
        - python
        - core
        - vscode
        - alacritty
  tasks:
    - import_tasks: tasks/core.yml
      become: true
    - import_tasks: tasks/dotfiles.yml
    - import_tasks: tasks/ssh.yml
    - import_tasks: tasks/gpg.yml
    - import_tasks: tasks/bat.yml
    - import_tasks: tasks/docker.yml
      become: true
    - import_tasks: tasks/git.yml
      become: true
    - import_tasks: tasks/fzf.yml
    - import_tasks: tasks/tmux.yml
    - import_tasks: tasks/asdf.yml
    - import_tasks: tasks/terraform.yml
      become: true
    - import_tasks: tasks/vscode.yml
      become: true
    - import_tasks: tasks/alacritty.yml

- name: Include node playbook
  ansible.builtin.import_playbook: playbooks/node.yml

- name: Include python playbook
  ansible.builtin.import_playbook: playbooks/python.yml
