- name: Install core packages
  apt:
    name: ["i3", "htop", "pavucontrol", "pipewire", "wireplumber", "pipewire-pulse"]
    state: latest
  become: true
  tags:
    - core

- name: Disable pulseaudio
  ansible.builtin.systemd:
    name: ["pulseaudio.service", "pulseaudio.socket"]
    enabled: false
  tags:
    - core

- name: Mask pulseaudio
  ansible.builtin.systemd:
    name: pulseaudio
    masked: true
  tags:
    - core

- name: Enable pipewire
  ansible.builtin.systemd:
    name: ["pipewire", "pipewire-pulse", "wireplumber"]
    enabled: true
  tags:
    - core

- name: Disable power saving in kernel
  shell: 'sudo tee /etc/modprobe.d/snd-hda-intel.conf <<< "options snd_hda_intel power_save=0"'
  tags:
    - core

- name: Install more packages
  apt:
    name: ["rofi", "playerctl", "tree", "picom", "stow", "keychain"]
    state: latest
  become: true
  tags:
    - core

- name: Disable fn lock
  shell: echo options hid_apple fnmode=2 | tee -a /etc/modprobe.d/hid_apple.conf
  become: true
  tags:
    - core

- name: Commit fn lock changes to initramfs
  shell: update-initramfs -u -k all
  become: true
  tags:
    - core

- name: Install backports polybar
  apt:
    name: polybar
    state: latest
    default_release: "$(lsb_release -cs)-backports"
  become: true
  tags:
    - core

