- name: Install Node
  apt:
    name: ['nodejs', 'npm']
    state: latest
  become: true
  tags:
    - node

- name: Set npm prefix
  shell: "npm config set prefix {{ lookup('env', 'HOME') }}/.npm"
  tags:
    - node

- name: Install Node v14
  shell: npx n 14
  environment:
    N_PREFIX: "{{ lookup('env', 'HOME') }}/.n"
  tags:
    - node

