- name: Check if packages.microsoft.gpg is installed
  stat:
    path: /etc/apt/keyrings/packages.microsoft.gpg
  register: microsoft_gpg
  tags:
    - vscode

- name: Install dependencies
  apt:
    name: ["wget", "gpg", "apt-transport-https"]
    state: present
  become: true
  tags:
    - vscode

- name: Download Microsoft GPG Key
  shell: "wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > {{ lookup('env', 'HOME') }}/packages.microsoft.gpg"
  become: true
  when: microsoft_gpg.stat.exists == False
  tags:
    - vscode

- name: Install Microsoft GPG Key
  shell: "install -D -o root -g root -m 644 {{ lookup('env', 'HOME') }}/packages.microsoft.gpg /etc/apt/keyrings/packages.microsoft.gpg"
  become: true
  when: microsoft_gpg.stat.exists == False
  tags:
    - vscode

- name: Add vscode repository
  shell: echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" > /etc/apt/sources.list.d/vscode.list
  become: true
  when: microsoft_gpg.stat.exists == False
  tags:
    - vscode

- name: Remove intermediate file
  file:
    path: "{{ lookup('env', 'HOME') }}/packages.microsoft.gpg"
    state: absent
  when: microsoft_gpg.stat.exists == False
  tags:
    - vscode

- name: Install vscode
  apt:
    name: code
    state: latest
    update_cache: true
  become: true
  tags:
    - vscode

